### ISSUE TITLE
No se esta guardando la información

### ISSUE THREAD

**Issue by cguillencr** [UCR-Paraiso-Lenguajes/B40129#1]
Buenas Daniel... En vista de que lo terminaste antes te paso mi retroalimentación para que haga las mejoras del caso.
1. En este video podes ver como la app no funciona como se especifica http://screencast.com/t/jV4fGD4VMa
2. Pienso que podes hacer una mejor propuesta de colores, como el mockup que les pase. En la vida real es difícil que te acepten un trabajo así, no porque esté malo, sino porque cuando los diseñadores hagan su revisión van a ver que generaste un entregable similar al que ellos propusieron.

**Comment by Dascr32** [comment]
Buenas profe, gracias por el feedback. Al parecer el error era en `usercontroller.js` en la funcion `getUsers()` no inicializaba la variable `users`, parece que a chrome le daba igual pero firefox del todo no. 

En cuanto a la propuesta de colores, estoy usando un tema de [bootswatch](https://bootswatch.com/lumen/), ese tema lo que busca es la simplicidad pero si se ve un poco sencillo como decís. Ahora agregue otro tema que tal vez se vea mas atractivo.

**Comment by Dascr32** [comment]
Arreglado en c1b9753f1c265a6bc21767b0bdd3ad1fdf57f401
